#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: The Exclusive Or

# Short bio or description (displayed in the header)
# description: On academic, expatriate, and other unusual forms of life eh....
description: How to be creative, productive, and happy as a researcher. Advice and reflections from a working scientist in machine learning.
tagline: Advice on how to be creative, productive, and happy as a researcher.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/xor.png

start-year: 2012

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: csutton@inf.ed.ac.uk
  facebook:
  flickr:
  github: casutton
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: RandomlyWalking
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
twitter:
  username: RandomlyWalking
  card: summary

social:
  name: Charles Sutton
  links:
    - label: "Research"
      icon: "fas fa-fw fa-link"
      url: "http://homepages.inf.ed.ac.uk/csutton/"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/charles-sutton-772aa126/"
    - label: "Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=hYtGXD0AAAAJ"
    - label: "Bluesky"
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/randomlywalking.bsky.social"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/RandomlyWalking"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/casutton"
    - label: "RSS"
      icon: "fa fa-rss"
      url: "{{ site.baseurl }}feed.xml"


author:
  name: Charles Sutton
  url: http://homepages.inf.ed.ac.uk/csutton/

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://www.theexclusive.org

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:year/:month/:title.html

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-include-cache
  - jekyll-paginate-v2 # Paginate front page

plugins:
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'  # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 10
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 5
    after: 5
